#!/bin/bash

# --- 0. Initial Setup & Privilege Check ---

# Extend sudo privileges to avoid repeated password prompts
sudo -v
echo "Sudo permissions granted for the script duration."

# --- Configuration Variables ---
OMZ_SHARED_DIR="/usr/share/oh-my-zsh"
OMZ_CUSTOM_SHARED_DIR="${OMZ_SHARED_DIR}/custom"
P10K_DIR="${OMZ_CUSTOM_SHARED_DIR}/themes/powerlevel10k"
AUTO_SUGGESTIONS_DIR="${OMZ_CUSTOM_SHARED_DIR}/plugins/zsh-autosuggestions"
SYNTAX_HIGHLIGHTING_DIR="${OMZ_CUSTOM_SHARED_DIR}/plugins/zsh-syntax-highlighting"

P10K_REPO="https://github.com/romkatv/powerlevel10k.git"
AUTO_SUGGESTIONS_REPO="https://github.com/zsh-users/zsh-autosuggestions.git"
SYNTAX_HIGHLIGHTING_REPO="https://github.com/zsh-users/zsh-syntax-highlighting.git"

SKEL_ZSHRC="/etc/skel/.zshrc"
PLUGINS="(git zsh-autosuggestions zsh-syntax-highlighting)"

# --- Elevated Command Functions ---

# Function to run commands with retained sudo permission
run_as_root() {
    # Since we used 'sudo -v', this command retains the privilege
    sudo sh -c "$1"
}

# Function to check if a command exists
command_exists () {
  command -v "$1" >/dev/null 2>&1
}

# Function to perform clean-up before installation
clean_up_previous_installs() {
    local DIR="$1"
    local NAME="$2"
    if [ -d "$DIR" ]; then
        echo "💣 Removing existing $NAME directory: $DIR"
        run_as_root "rm -rf \"$DIR\""
    fi
}

# Function to force a fresh clone
force_git_clone() {
    local DIR="$1"
    local REPO="$2"
    local NAME="$3"

    clean_up_previous_installs "$DIR" "$NAME"

    echo "✨ Installing $NAME..."
    if run_as_root "git clone --depth=1 \"$REPO\" \"$DIR\""; then
        echo "✅ $NAME installed successfully."
    else
        echo "❌ Error: Failed to clone $NAME from $REPO. Exiting."
        exit 1
    fi
}

# --- 1. Install/Check Zsh and Git Packages ---
echo "--- 1. Checking/Installing Zsh and Git Packages ---"

# Determine the package manager
declare PKG_INSTALL
if command_exists apt; then
  PKG_INSTALL="apt update && apt install -y"
elif command_exists dnf; then
  PKG_INSTALL="dnf install -y"
elif command_exists pacman; then
  PKG_INSTALL="pacman -S --noconfirm"
else
  echo "Error: Cannot find a supported package manager (apt, dnf, pacman). Exiting."
  exit 1
fi

ZSH_BIN=$(command -v zsh)
GIT_BIN=$(command -v git)

if [ -z "$ZSH_BIN" ] || [ -z "$GIT_BIN" ]; then
    echo "Zsh or Git missing. Installing packages..."
    run_as_root "$PKG_INSTALL zsh git curl wget"
    ZSH_BIN=$(command -v zsh)
    if [ -z "$ZSH_BIN" ]; then
        echo "Fatal Error: Zsh installation failed. Exiting."
        exit 1
    fi
else
    echo "Zsh and Git are already installed."
fi

# --- 2. Set Zsh as the default shell for NEW user creation ---
echo "--- 2. Setting Zsh as the default shell for NEW users ---"
if [ -f /etc/adduser.conf ]; then
    run_as_root "sed -i 's/^DSHELL=.*$/DSHELL=\/bin\/zsh/' /etc/adduser.conf"
fi
if [ -f /etc/default/useradd ]; then
    run_as_root "sed -i 's/^SHELL=.*$/SHELL=\/bin\/zsh/' /etc/default/useradd"
fi
echo "New user defaults updated."

# --- 3. Clean and Install Oh My Zsh Framework ---
echo "--- 3. Clean and Install Oh My Zsh Framework ---"
force_git_clone "${OMZ_SHARED_DIR}" "https://github.com/ohmyzsh/ohmyzsh.git" "Oh My Zsh"
run_as_root "mkdir -p ${OMZ_CUSTOM_SHARED_DIR}/themes ${OMZ_CUSTOM_SHARED_DIR}/plugins" # Recreate custom folders

# --- 4. Clean and Install Powerlevel10k Theme ---
echo "--- 4. Clean and Install Powerlevel10k Theme ---"
force_git_clone "$P10K_DIR" "$P10K_REPO" "Powerlevel10k"

# --- 5. Clean and Install Zsh Plugins ---
echo "--- 5. Clean and Install Zsh Plugins (Autosuggestions, Syntax-Highlighting) ---"
force_git_clone "$AUTO_SUGGESTIONS_DIR" "$AUTO_SUGGESTIONS_REPO" "zsh-autosuggestions"
force_git_clone "$SYNTAX_HIGHLIGHTING_DIR" "$SYNTAX_HIGHLIGHTING_REPO" "zsh-syntax-highlighting"


# --- 6. Configure /etc/skel for New Users ---
echo "--- 6. Configuring /etc/skel for new users ---"

# a. Copy the OMZ template to skel (ensures fresh copy of zshrc template)
echo "Creating fresh $SKEL_ZSHRC template..."
run_as_root "cp ${OMZ_SHARED_DIR}/templates/zshrc.zsh-template ${SKEL_ZSHRC}"
run_as_root "chmod 644 $SKEL_ZSHRC"

# b. Update the ZSH path, theme, and plugins in /etc/skel/.zshrc
echo "Applying Zsh configuration settings to $SKEL_ZSHRC..."
# 1. Set the global ZSH path
run_as_root "sed -i 's|^export ZSH=.*$|export ZSH=\"${OMZ_SHARED_DIR}\"|' ${SKEL_ZSHRC}"
# 2. Set the Powerlevel10k theme
run_as_root "sed -i 's|^ZSH_THEME=.*$|ZSH_THEME=\"powerlevel10k\/powerlevel10k\"|' ${SKEL_ZSHRC}"
# 3. Set the plugins
run_as_root "sed -i 's|^plugins=.*$|plugins=$PLUGINS|' ${SKEL_ZSHRC}"

# c. Create p10k config file placeholder
run_as_root "touch /etc/skel/.p10k.zsh"
run_as_root "echo '# Powerlevel10k configuration (auto-generated by p10k configure)' > /etc/skel/.p10k.zsh"
run_as_root "chmod 644 /etc/skel/.p10k.zsh"

echo "--- System Setup/Update Complete 🎉 ---"
echo "✅ Zsh, Oh My Zsh, Powerlevel10k, and plugins have been **force-cleaned and reinstalled** to the latest version."
echo "✅ Configuration files for new users are ready in /etc/skel."
echo ""
echo "🔥 **IMPORTANT NEXT STEPS (For ALL Users):**"
echo "1. **Font Install:** Each user must manually install a Nerd Font (like **MesloLGS NF**) on their OS and set their terminal to use it."
echo "2. **New Shell:** Users must **log out and log back in** to start using Zsh."
echo "3. **Configuration:** The **Powerlevel10k wizard** will automatically start for each user on their first Zsh launch. To re-run, type: **p10k configure**"
