#!/bin/bash

# --- 0. Initial Setup & Privilege Check ---

# Extend sudo privileges to avoid repeated password prompts
sudo -v
echo "Sudo permissions granted for the script duration."

# --- Configuration Variables ---
OMZ_SHARED_DIR="/usr/share/oh-my-zsh"
OMZ_CUSTOM_SHARED_DIR="${OMZ_SHARED_DIR}/custom"
P10K_DIR="${OMZ_CUSTOM_SHARED_DIR}/themes/powerlevel10k"
AUTO_SUGGESTIONS_DIR="${OMZ_CUSTOM_SHARED_DIR}/plugins/zsh-autosuggestions"
SYNTAX_HIGHLIGHTING_DIR="${OMZ_CUSTOM_SHARED_DIR}/plugins/zsh-syntax-highlighting"

P10K_REPO="https://github.com/romkatv/powerlevel10k.git"
AUTO_SUGGESTIONS_REPO="https://github.com/zsh-users/zsh-autosuggestions.git"
SYNTAX_HIGHLIGHTING_REPO="https://github.com/zsh-users/zsh-syntax-highlighting.git"

SKEL_ZSHRC="/etc/skel/.zshrc"
PLUGINS="(git zsh-autosuggestions zsh-syntax-highlighting)"
CURRENT_USER=$(whoami)

# --- Elevated Command Functions ---

# Function to run commands with retained sudo permission
run_as_root() {
    sudo sh -c "$1"
}

# Function to run commands as the original user (not root)
run_as_user() {
    sudo -u "$CURRENT_USER" sh -c "$1"
}

# Function to check if a command exists
command_exists () {
  command -v "$1" >/dev/null 2>&1
}

# Function to perform clean-up before installation
clean_up_previous_installs() {
    local DIR="$1"
    local NAME="$2"
    if [ -d "$DIR" ]; then
        echo "💣 Removing existing $NAME directory: $DIR"
        run_as_root "rm -rf \"$DIR\""
    fi
}

# Function to force a fresh clone
force_git_clone() {
    local DIR="$1"
    local REPO="$2"
    local NAME="$3"

    clean_up_previous_installs "$DIR" "$NAME"

    echo "✨ Installing $NAME..."
    if run_as_root "git clone --depth=1 \"$REPO\" \"$DIR\""; then
        echo "✅ $NAME installed successfully."
    else
        echo "❌ Error: Failed to clone $NAME from $REPO. Exiting."
        exit 1
    fi
}

# --- 1. Install/Check Zsh and Git Packages ---
echo "--- 1. Checking/Installing Zsh and Git Packages ---"

# Determine the package manager
declare PKG_INSTALL
if command_exists apt; then
  PKG_INSTALL="apt update && apt install -y"
elif command_exists dnf; then
  PKG_INSTALL="dnf install -y"
elif command_exists pacman; then
  PKG_INSTALL="pacman -S --noconfirm"
else
  echo "Error: Cannot find a supported package manager (apt, dnf, pacman). Exiting."
  exit 1
fi

ZSH_BIN=$(command -v zsh)
GIT_BIN=$(command -v git)

if [ -z "$ZSH_BIN" ] || [ -z "$GIT_BIN" ]; then
    echo "Zsh or Git missing. Installing packages..."
    run_as_root "$PKG_INSTALL zsh git curl wget"
    ZSH_BIN=$(command -v zsh)
    if [ -z "$ZSH_BIN" ]; then
        echo "Fatal Error: Zsh installation failed. Exiting."
        exit 1
    fi
else
    echo "Zsh and Git are already installed."
fi

# --- 2. Set Zsh as the default shell for NEW user creation ---
echo "--- 2. Setting Zsh as the default shell for NEW users ---"
if [ -f /etc/adduser.conf ]; then
    run_as_root "sed -i 's/^DSHELL=.*$/DSHELL=\/bin\/zsh/' /etc/adduser.conf"
fi
if [ -f /etc/default/useradd ]; then
    run_as_root "sed -i 's/^SHELL=.*$/SHELL=\/bin\/zsh/' /etc/default/useradd"
fi
echo "New user defaults updated."

# --- 3. Clean and Install Oh My Zsh Framework ---
echo "--- 3. Clean and Install Oh My Zsh Framework ---"
force_git_clone "${OMZ_SHARED_DIR}" "https://github.com/ohmyzsh/ohmyzsh.git" "Oh My Zsh"
run_as_root "mkdir -p ${OMZ_CUSTOM_SHARED_DIR}/themes ${OMZ_CUSTOM_SHARED_DIR}/plugins" # Recreate custom folders

# --- 4. Clean and Install Powerlevel10k Theme ---
echo "--- 4. Clean and Install Powerlevel10k Theme ---"
force_git_clone "$P10K_DIR" "$P10K_REPO" "Powerlevel10k"

# --- 5. Clean and Install Zsh Plugins ---
echo "--- 5. Clean and Install Zsh Plugins (Autosuggestions, Syntax-Highlighting) ---"
force_git_clone "$AUTO_SUGGESTIONS_DIR" "$AUTO_SUGGESTIONS_REPO" "zsh-autosuggestions"
force_git_clone "$SYNTAX_HIGHLIGHTING_DIR" "$SYNTAX_HIGHLIGHTING_REPO" "zsh-syntax-highlighting"


# --- 6. Configure /etc/skel for New Users ---
echo "--- 6. Configuring /etc/skel for new users ---"

# a. Copy the OMZ template to skel
echo "Creating fresh $SKEL_ZSHRC template..."
run_as_root "cp ${OMZ_SHARED_DIR}/templates/zshrc.zsh-template ${SKEL_ZSHRC}"
run_as_root "chmod 644 $SKEL_ZSHRC"

# b. Update the ZSH path, theme, and plugins in /etc/skel/.zshrc
echo "Applying Zsh configuration settings to $SKEL_ZSHRC..."
run_as_root "sed -i 's|^export ZSH=.*$|export ZSH=\"${OMZ_SHARED_DIR}\"|' ${SKEL_ZSHRC}"
run_as_root "sed -i 's|^ZSH_THEME=.*$|ZSH_THEME=\"powerlevel10k\/powerlevel10k\"|' ${SKEL_ZSHRC}"
run_as_root "sed -i 's|^plugins=.*$|plugins=$PLUGINS|' ${SKEL_ZSHRC}"

# c. Create p10k config file placeholder
run_as_root "touch /etc/skel/.p10k.zsh"
run_as_root "echo '# Powerlevel10k configuration (auto-generated by p10k configure)' > /etc/skel/.p10k.zsh"
run_as_root "chmod 644 /etc/skel/.p10k.zsh"


# --- 7. Final Step: Configure Current User's Shell and Setup Zsh ---
echo "--- 7. Configuring Current User ($CURRENT_USER) Shell ---"

# a. Set Zsh as the default shell for the current user
if [ "$(dscl . -read /Users/$CURRENT_USER UserShell 2>/dev/null | awk '{print $2}')" != "$ZSH_BIN" ]; then
    # Use chsh if available (most Linux/Unix systems)
    if command_exists chsh; then
        echo "Setting Zsh as default shell for $CURRENT_USER using chsh."
        # The user's password may be required here, separate from the initial sudo -v
        chsh -s "$ZSH_BIN" "$CURRENT_USER"
    else
        echo "Warning: 'chsh' command not found. You must manually change your shell via your user management tools."
    fi
fi

# b. Copy the /etc/skel files to the current user's home directory
echo "Copying global config to current user's home directory (~/.zshrc and ~/.p10k.zsh)..."
run_as_user "cp -n /etc/skel/.zshrc $HOME/.zshrc"
run_as_user "cp -n /etc/skel/.p10k.zsh $HOME/.p10k.zsh"

# c. Run Zsh now to trigger configuration wizard
echo ""
echo "======================================================================"
echo "Setup Complete! Starting Zsh now for initial configuration."
echo "You must **log out and log back in** for Zsh to become your permanent default shell."
echo "======================================================================"

# Execute Zsh, which will trigger p10k configure on first run
exec "$ZSH_BIN"
